// Generated by Void Manifest Engine
// Submit exercise answer

import { NextRequest, NextResponse } from 'next/server'
import { authenticate } from '@/lib/auth'
import { prisma } from '@/lib/prisma'

export async function post(request: NextRequest) {
  const user = await authenticate(request)
  if (!user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const body = await request.json()
  // Check exercise answer, update progress, track mistake patterns. Return correction with explanation.

  const item = await prisma.Exercise.create({ data: body })
  return NextResponse.json(item, { status: 201 })
}