// Generated by Void Manifest Engine
// Get assessment history

import { NextRequest, NextResponse } from 'next/server'
import { authenticate } from '@/lib/auth'
import { prisma } from '@/lib/prisma'

export async function get(request: NextRequest) {
  const user = await authenticate(request)
  if (!user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  // Get assessment history with scores and recommendations

  const items = await prisma.Assessment.findMany()
  return NextResponse.json(items)
}