// Generated by Void Manifest Engine
// Get progress dashboard

import { NextRequest, NextResponse } from 'next/server'
import { authenticate } from '@/lib/auth'
import { prisma } from '@/lib/prisma'

export async function get(request: NextRequest) {
  const user = await authenticate(request)
  if (!user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  // Get user progress summary: completed lessons, scores, time spent, weak areas

  const items = await prisma.Progress.findMany()
  return NextResponse.json(items)
}