// Generated by Void Manifest Engine
// Get personalized lessons

import { NextRequest, NextResponse } from 'next/server'
import { authenticate } from '@/lib/auth'
import { prisma } from '@/lib/prisma'

export async function get(request: NextRequest) {
  const user = await authenticate(request)
  if (!user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  // List lessons filtered by learner category, level, and skill focus area. Sort by recommended order.

  const items = await prisma.Lesson.findMany()
  return NextResponse.json(items)
}