// Generated by Void Manifest Engine
// List of past assessments with scores

'use client'

import { useState } from 'react'

interface AssessmentHistoryProps {
  assessments: Assessment[]
}

export default function AssessmentHistory({ assessments }: AssessmentHistoryProps) {
  return (
    <div className="space-y-2">
      {assessments.length === 0 && <p className="text-gray-400 text-center py-4">Nothing here yet</p>}
      {assessments.map((assessment) => (
        <AssessmentCard key={assessment.id} {assessment={assessment}} />
      ))}
    </div>
  )
}