// Generated by Void Manifest Engine
// Audio player with speed control

'use client'

import { useState } from 'react'

interface AudioPlayerProps {
  audioUrl: string
}

export default function AudioPlayer({ audioUrl }: AudioPlayerProps) {
  const [playing, setPlaying] = useState(false)
  const audioRef = useState(null)

  const togglePlay = () => {
    if (!audioRef[0]) {
      const audio = new Audio({audioUrl})
      audio.onended = () => setPlaying(false)
      audioRef[1](audio)
      audio.play()
      setPlaying(true)
    } else if (playing) {
      audioRef[0].pause()
      setPlaying(false)
    } else {
      audioRef[0].play()
      setPlaying(true)
    }
  }

  return (
    <div className="flex items-center gap-3 p-3 rounded-lg border bg-white">
      <button onClick={togglePlay} className="w-10 h-10 rounded-full bg-blue-600 text-white flex items-center justify-center hover:bg-blue-700 transition">
        {playing ? '⏸' : '▶'}
      </button>
      <span className="text-sm text-gray-600">{comp.description}</span>
      <div className="flex-1 h-1 bg-gray-200 rounded-full"><div className={"h-full bg-blue-500 rounded-full transition-all " + (playing ? "w-3/4" : "w-0")} /></div>
    </div>
  )
}