// Generated by Void Manifest Engine
// Grid of earned and locked badges

'use client'

import { useState } from 'react'

interface BadgeGridProps {
  badges: Achievement[]
}

export default function BadgeGrid({ badges }: BadgeGridProps) {
  return (
    <div className="grid grid-cols-3 gap-4">
      {badges.length === 0 && <p className="text-gray-400 text-center py-4">Nothing here yet</p>}
      {badges.map((badge) => (
        <StreakBadge key={badge.id} {badge={badge}} />
      ))}
    </div>
  )
}