// Generated by Void Manifest Engine
// Filter tabs for lesson categories

'use client'

import { useState } from 'react'

interface CategoryFilterProps {
  categories: any[]
  active?: string
}

export default function CategoryFilter({ categories, active }: CategoryFilterProps) {
  const [activeTab, setActiveTab] = useState(0)

  return (
    <div className="flex flex-wrap gap-2">
      {categories && categories.map((item, i) => (
        <button key={i} onClick={() => setActiveTab(i)}
                className={"px-4 py-2 rounded-full text-sm font-medium transition " + 
                  (i === activeTab ? "bg-blue-600 text-white" : "bg-gray-100 text-gray-600 hover:bg-gray-200")}>
          {item.name || item.label || item}
        </button>
      ))}
    </div>
  )
}