// Generated by Void Manifest Engine
// Today's recommended lesson with difficulty and duration

'use client'

import { useState } from 'react'

interface DailyLessonCardProps {
  lesson: Lesson
}

export default function DailyLessonCard({ lesson }: DailyLessonCardProps) {
  return (
    <div className="rounded-lg border p-4 shadow-sm bg-white">
      <div className="text-2xl mb-2">📚</div>
      <h3 className="font-semibold text-gray-900">{lesson}</h3>
      <p className="text-xs text-gray-400 mt-2">{comp.description}</p>
    </div>
  )
}