// Generated by Void Manifest Engine
// Weekly leaderboard

'use client'

import { useState } from 'react'

export default function LeaderboardCard() {
  return (
    <div className="rounded-lg border p-4 shadow-sm bg-white">
      <div className="text-2xl mb-2">🏆</div>
      <p className="text-xs text-gray-400 mt-2">{comp.description}</p>
    </div>
  )
}