// Generated by Void Manifest Engine
// Filterable list of lessons by category and level

'use client'

import { useState } from 'react'

interface LessonListProps {
  lessons: Lesson[]
}

export default function LessonList({ lessons }: LessonListProps) {
  return (
    <div className="space-y-2">
      {lessons.length === 0 && <p className="text-gray-400 text-center py-4">Nothing here yet</p>}
      {lessons.map((lesson) => (
        <DailyLessonCard key={lesson.id} {lesson={lesson}} />
      ))}
    </div>
  )
}