// Generated by Void Manifest Engine
// Lesson content display with text and visuals

'use client'

import { useState } from 'react'

interface LessonContentProps {
  lesson: Lesson
}

export default function LessonContent({ lesson }: LessonContentProps) {
  const [flipped, setFlipped] = useState(false)

  return (
    <div className="relative w-full h-48 cursor-pointer" onClick={() => setFlipped(!flipped)}>
      <div className={"absolute inset-0 transition-transform duration-500 " + (flipped ? "rotateY-180" : "")}>
        <div className="rounded-lg border p-6 shadow-md bg-white h-full flex flex-col justify-center items-center">
          <div className="text-2xl font-bold text-gray-900">{lesson.title}</div>
        </div>
      </div>
    </div>
  )
}