// Generated by Void Manifest Engine
// CEFR level badge (A1-C2)

'use client'

import { useState } from 'react'

interface LevelIndicatorProps {
  level: string
}

export default function LevelIndicator({ level }: LevelIndicatorProps) {
  return (
    <div className="rounded-lg border p-4 shadow-sm bg-white">
      <div className="text-2xl mb-2">🎯</div>
      <h3 className="font-semibold text-gray-900">{level}</h3>
      <p className="text-xs text-gray-400 mt-2">{comp.description}</p>
    </div>
  )
}