// Generated by Void Manifest Engine
// Phonetic breakdown with IPA and audio

'use client'

import { useState } from 'react'

interface PhoneticGuideProps {
  word: string
  phonetic: string
}

export default function PhoneticGuide({ word, phonetic }: PhoneticGuideProps) {
  const [flipped, setFlipped] = useState(false)

  return (
    <div className="relative w-full h-48 cursor-pointer" onClick={() => setFlipped(!flipped)}>
      <div className={"absolute inset-0 transition-transform duration-500 " + (flipped ? "rotateY-180" : "")}>
        <div className="rounded-lg border p-6 shadow-md bg-white h-full flex flex-col justify-center items-center">
          <div className="text-2xl font-bold text-gray-900">{word.english}</div>
          <p className="text-gray-600 mt-1">{phonetic}</p>
        </div>
      </div>
    </div>
  )
}