// Generated by Void Manifest Engine
// Time-series progress chart

'use client'

import { useState } from 'react'

interface ProgressChartProps {
  data: any[]
}

export default function ProgressChart({ data }: ProgressChartProps) {
  return (
    <div className="rounded-lg border p-4 bg-white">
      <h4 className="text-sm font-medium text-gray-500 mb-3">{comp.description}</h4>
      <div className="space-y-2">
        {data && data.map((item) => (
          <div key={item.name || item.label} className="flex items-center gap-2">
            <span className="text-xs text-gray-600 w-20 truncate">{item.name || item.label}</span>
            <div className="flex-1 h-4 bg-gray-100 rounded-full overflow-hidden">
              <div className="h-full bg-blue-500 rounded-full transition-all"
                    style={{width: `${(item.value || item.percent || 0)}%`}} />
            </div>
            <span className="text-xs text-gray-500 w-10 text-right">{item.value || item.percent}%</span>
          </div>
        ))}
      </div>
    </div>
  )
}