// Generated by Void Manifest Engine
// Summary card showing lessons done, words learned, streak

'use client'

import { useState } from 'react'

interface ProgressSummaryProps {
  progress: any[]
  user: User
}

export default function ProgressSummary({ progress, user }: ProgressSummaryProps) {
  return (
    <div className="rounded-lg border p-4 shadow-sm bg-white animate-pulse">
      <div className="text-2xl mb-2">📊</div>
      <h3 className="font-semibold text-gray-900">{progress}</h3>
      <p className="text-sm text-gray-600 mt-1">{user}</p>
      <p className="text-xs text-gray-400 mt-2">{comp.description}</p>
    </div>
  )
}