// Generated by Void Manifest Engine
// Circular progress indicator

'use client'

import { useState } from 'react'

interface ProgressRingProps {
  percent: number
  label: string
}

export default function ProgressRing({ percent, label }: ProgressRingProps) {
  return (
    <div className="flex flex-col items-center justify-center">
      <svg width={100} height={100} className="transform -rotate-90">
        <circle cx={50} cy={50} r={42} fill="none"
                stroke="#e5e7eb" strokeWidth={8} />
        <circle cx={50} cy={50} r={42} fill="none"
                stroke="currentColor" strokeWidth={8}
                className="text-emerald-500 transition-all duration-1000"
                strokeDasharray={263.89356}
                strokeDashoffset={{263.89356} - ({{percent}} / 100) * {263.89356}}
                strokeLinecap="round" />
      </svg>
      <div className="text-2xl font-bold text-emerald-600 mt-2">{percent}%</div>
      <div className="text-sm text-gray-500">{label}</div>
    </div>
  )
}