// Generated by Void Manifest Engine
// Play pronunciation audio button

'use client'

import { useState } from 'react'

interface PronunciationButtonProps {
  audioUrl: string
  word: string
}

export default function PronunciationButton({ audioUrl, word }: PronunciationButtonProps) {
  const [playing, setPlaying] = useState(false)
  const audioRef = useState(null)

  const togglePlay = () => {
    if (!audioRef[0]) {
      const audio = new Audio({audioUrl})
      audio.onended = () => setPlaying(false)
      audioRef[1](audio)
      audio.play()
      setPlaying(true)
    } else if (playing) {
      audioRef[0].pause()
      setPlaying(false)
    } else {
      audioRef[0].play()
      setPlaying(true)
    }
  }

  return (
    <div className="flex items-center gap-3 p-3 rounded-lg border bg-white">
      <button onClick={togglePlay} className="w-10 h-10 rounded-full bg-blue-600 text-white flex items-center justify-center hover:bg-blue-700 transition">
        {playing ? '⏸' : '▶'}
      </button>
      <span className="font-medium text-gray-900">{word}</span>
    </div>
  )
}