// Generated by Void Manifest Engine
// Radar chart of skill assessment results

'use client'

import { useState } from 'react'

interface SkillRadarProps {
  skills: any[]
}

export default function SkillRadar({ skills }: SkillRadarProps) {
  return (
    <div className="rounded-lg border p-4 bg-white">
      <h4 className="text-sm font-medium text-gray-500 mb-3">{comp.description}</h4>
      <div className="space-y-1">
        {skills && skills.map((item) => (
          <div key={item.name} className="flex items-center justify-between text-sm">
            <span>{item.name}</span>
            <div className="flex gap-1">
              {Array.from({length: 5}, (_, i) => (
                <div key={i} className={"w-3 h-3 rounded-full " + (i < (item.level||0) ? "bg-indigo-500" : "bg-gray-200")} />
              ))}
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}