// Generated by Void Manifest Engine
// SRS timer showing when words are due next

'use client'

import { useState } from 'react'

interface SpacedRepetitionTimerProps {
  nextReview: string
}

export default function SpacedRepetitionTimer({ nextReview }: SpacedRepetitionTimerProps) {
  const [timeLeft, setTimeLeft] = useState('')

  useState(() => {
    const target = new Date({nextReview}).getTime()
    const tick = () => {
      const diff = target - Date.now()
      if (diff <= 0) { setTimeLeft('Ready!'); return }
      const h = Math.floor(diff / 3600000)
      const m = Math.floor((diff % 3600000) / 60000)
      setTimeLeft(`${h}h ${m}m`)
    }
    tick()
    const interval = setInterval(tick, 60000)
    return () => clearInterval(interval)
  }, [])

  return (
    <div className="rounded-lg border p-4 text-center bg-white">
      <p className="text-xs text-gray-500 uppercase tracking-wide">{label}</p>
      <div className="text-2xl font-bold text-purple-600 mt-1">{timeLeft || "..."}</div>
    </div>
  )
}