// Generated by Void Manifest Engine
// Large animated streak counter

'use client'

import { useState } from 'react'

interface StreakCounterProps {
  days: number
}

export default function StreakCounter({ days }: StreakCounterProps) {
  return (
    <div className="rounded-lg border p-4 shadow-sm bg-white animate-pulse">
      <div className="text-2xl mb-2">⚡</div>
      <div className="text-3xl font-bold text-orange-600">{days}</div>
      <div className="text-sm text-gray-500 mt-1">{days}</div>
      <p className="text-xs text-gray-400 mt-2">{comp.description}</p>
    </div>
  )
}