// Generated by Void Manifest Engine
// Current study streak with fire icon

'use client'

import { useState } from 'react'

interface StreakBadgeProps {
  streak: number
}

export default function StreakBadge({ streak }: StreakBadgeProps) {
  return (
    <div className="rounded-lg border p-4 shadow-sm bg-white animate-pulse">
      <div className="text-2xl mb-2">🔥</div>
      <div className="text-3xl font-bold text-orange-600">{streak}</div>
      <div className="text-sm text-gray-500 mt-1">{streak}</div>
      <p className="text-xs text-gray-400 mt-2">{comp.description}</p>
    </div>
  )
}