// Generated by Void Manifest Engine
// GitHub-style heatmap calendar

'use client'

import { useState } from 'react'

interface StudyStreakCalendarProps {
  sessions: any[]
}

export default function StudyStreakCalendar({ sessions }: StudyStreakCalendarProps) {
  return (
    <div className="rounded-lg border p-4 shadow-sm bg-white">
      <div className="text-2xl mb-2">📅</div>
      <h3 className="font-semibold text-gray-900">{sessions}</h3>
      <p className="text-xs text-gray-400 mt-2">{comp.description}</p>
    </div>
  )
}