// Generated by Void Manifest Engine
// Alert showing skill areas needing practice

'use client'

import { useState } from 'react'

interface WeakAreasAlertProps {
  weakAreas: any[]
}

export default function WeakAreasAlert({ weakAreas }: WeakAreasAlertProps) {
  return (
    <div className="rounded-lg border p-4 shadow-sm bg-white">
      <div className="text-2xl mb-2">⚠️</div>
      <h3 className="font-semibold text-gray-900">{weakAreas}</h3>
      <p className="text-xs text-gray-400 mt-2">{comp.description}</p>
    </div>
  )
}