// Generated by Void Manifest Engine
// Flashcard-style word card with flip animation

'use client'

import { useState } from 'react'

interface WordCardProps {
  word: Word
  onReview: () => void
}

export default function WordCard({ word, onReview }: WordCardProps) {
  const [flipped, setFlipped] = useState(false)

  return (
    <div className="relative w-full h-48 cursor-pointer" onClick={() => setFlipped(!flipped)}>
      <div className={"absolute inset-0 transition-transform duration-500 " + (flipped ? "rotateY-180" : "")}>
        <div className="rounded-lg border p-6 shadow-md bg-white h-full flex flex-col justify-center items-center">
          <div className="text-2xl font-bold text-gray-900">{word.english}</div>
        </div>
      </div>
    </div>
  )
}