// Generated by Void Manifest Engine
// Words due for spaced repetition review

'use client'

import { useState } from 'react'

interface WordReviewWidgetProps {
  words: Word[]
}

export default function WordReviewWidget({ words }: WordReviewWidgetProps) {
  return (
    <div className="rounded-lg border p-4 shadow-sm bg-white">
      <div className="text-2xl mb-2">📝</div>
      <h3 className="font-semibold text-gray-900">{words}</h3>
      <p className="text-xs text-gray-400 mt-2">{comp.description}</p>
    </div>
  )
}