// Generated by Void Manifest Engine
// Word search with autocomplete

'use client'

import { useState } from 'react'

interface WordSearchInputProps {
  onSearch: () => void
}

export default function WordSearchInput({ onSearch }: WordSearchInputProps) {
  const [activeTab, setActiveTab] = useState(0)

  return (
    <div className="flex flex-wrap gap-2">
      {onSearch && onSearch.map((item, i) => (
        <button key={i} onClick={() => setActiveTab(i)}
                className={"px-4 py-2 rounded-full text-sm font-medium transition " + 
                  (i === activeTab ? "bg-blue-600 text-white" : "bg-gray-100 text-gray-600 hover:bg-gray-200")}>
          {item.name || item.label || item}
        </button>
      ))}
    </div>
  )
}